// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_dsMainSCREEN = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_dsMainValue = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_dsCaption1 = NULL;
lv_obj_t * ui_dsCostToday = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_dsCaption2 = NULL;
lv_obj_t * ui_dsTokens = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_dsCaption3 = NULL;
lv_obj_t * ui_dsCostTotal = NULL;
// event funtions
void ui_event_dsMainSCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_kimiMainSCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_kimiMainSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_overviewSCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_overviewSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_dsInfoSCREEN, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_dsInfoSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_overviewSCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_overviewSCREEN_screen_init);
    }
}

// build funtions

void ui_dsMainSCREEN_screen_init(void)
{
    ui_dsMainSCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dsMainSCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_dsMainSCREEN);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(100));
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container6, &ui_img_919862230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 246);
    lv_obj_set_height(ui_Container15, 22);
    lv_obj_set_x(ui_Container15, -30);
    lv_obj_set_y(ui_Container15, -174);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsMainValue = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_dsMainValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsMainValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsMainValue, -5);
    lv_obj_set_y(ui_dsMainValue, -193);
    lv_obj_set_align(ui_dsMainValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsMainValue, "--");
    lv_obj_set_style_text_color(ui_dsMainValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsMainValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsMainValue, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 246);
    lv_obj_set_height(ui_Container16, 15);
    lv_obj_set_x(ui_Container16, -30);
    lv_obj_set_y(ui_Container16, -174);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 260);
    lv_obj_set_height(ui_Container7, 45);
    lv_obj_set_x(ui_Container7, -152);
    lv_obj_set_y(ui_Container7, -127);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsCaption1 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_dsCaption1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsCaption1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsCaption1, -86);
    lv_obj_set_y(ui_dsCaption1, -125);
    lv_obj_set_align(ui_dsCaption1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsCaption1, "Today:");
    lv_obj_set_style_text_color(ui_dsCaption1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsCaption1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsCaption1, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsCostToday = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_dsCostToday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsCostToday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsCostToday, 33);
    lv_obj_set_y(ui_dsCostToday, -126);
    lv_obj_set_align(ui_dsCostToday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsCostToday, "--");
    lv_obj_set_style_text_color(ui_dsCostToday, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsCostToday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsCostToday, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 260);
    lv_obj_set_height(ui_Container13, 45);
    lv_obj_set_x(ui_Container13, -100);
    lv_obj_set_y(ui_Container13, -131);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsCaption2 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_dsCaption2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsCaption2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsCaption2, -88);
    lv_obj_set_y(ui_dsCaption2, -68);
    lv_obj_set_align(ui_dsCaption2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsCaption2, "Est.Tokens:");
    lv_obj_set_style_text_color(ui_dsCaption2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsCaption2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsCaption2, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsTokens = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_dsTokens, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsTokens, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsTokens, 26);
    lv_obj_set_y(ui_dsTokens, -71);
    lv_obj_set_align(ui_dsTokens, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_dsTokens, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_dsTokens, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_dsTokens, "--");
    lv_obj_set_style_text_color(ui_dsTokens, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsTokens, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsTokens, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 260);
    lv_obj_set_height(ui_Container14, 45);
    lv_obj_set_x(ui_Container14, -116);
    lv_obj_set_y(ui_Container14, -170);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsCaption3 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_dsCaption3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsCaption3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsCaption3, -91);
    lv_obj_set_y(ui_dsCaption3, -21);
    lv_obj_set_align(ui_dsCaption3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsCaption3, "Total:");
    lv_obj_set_style_text_color(ui_dsCaption3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsCaption3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsCaption3, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsCostTotal = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_dsCostTotal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsCostTotal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsCostTotal, 41);
    lv_obj_set_y(ui_dsCostTotal, -17);
    lv_obj_set_align(ui_dsCostTotal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsCostTotal, "--");
    lv_obj_set_style_text_color(ui_dsCostTotal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsCostTotal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsCostTotal, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_dsMainSCREEN, ui_event_dsMainSCREEN, LV_EVENT_ALL, NULL);

}

void ui_dsMainSCREEN_screen_destroy(void)
{
    if(ui_dsMainSCREEN) lv_obj_del(ui_dsMainSCREEN);

    // NULL screen variables
    ui_dsMainSCREEN = NULL;
    ui_Container6 = NULL;
    ui_Container15 = NULL;
    ui_dsMainValue = NULL;
    ui_Container16 = NULL;
    ui_Container7 = NULL;
    ui_dsCaption1 = NULL;
    ui_dsCostToday = NULL;
    ui_Container13 = NULL;
    ui_dsCaption2 = NULL;
    ui_dsTokens = NULL;
    ui_Container14 = NULL;
    ui_dsCaption3 = NULL;
    ui_dsCostTotal = NULL;

}

void ui_dsMainSCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
