// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DSMAINSCREEN_H
#define UI_DSMAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dsMainSCREEN
extern void ui_dsMainSCREEN_screen_init(void);
extern void ui_dsMainSCREEN_screen_destroy(void);
extern void ui_dsMainSCREEN_screen_relocalize(void);
extern void ui_event_dsMainSCREEN(lv_event_t * e);
extern lv_obj_t * ui_dsMainSCREEN;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_dsMainValue;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_dsCaption1;
extern lv_obj_t * ui_dsCostToday;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_dsCaption2;
extern lv_obj_t * ui_dsTokens;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_dsCaption3;
extern lv_obj_t * ui_dsCostTotal;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

