// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_dsInfoSCREEN = NULL;
lv_obj_t * ui_Container35 = NULL;
lv_obj_t * ui_Container40 = NULL;
lv_obj_t * ui_Container36 = NULL;
lv_obj_t * ui_dsInfoCaption1 = NULL;
lv_obj_t * ui_dsState = NULL;
lv_obj_t * ui_Container38 = NULL;
lv_obj_t * ui_dsInfoCaption2 = NULL;
lv_obj_t * ui_dsPlan = NULL;
lv_obj_t * ui_Container37 = NULL;
lv_obj_t * ui_dsInfoCaption3 = NULL;
lv_obj_t * ui_dsCash = NULL;
lv_obj_t * ui_Container39 = NULL;
lv_obj_t * ui_dsInfoCaption4 = NULL;
lv_obj_t * ui_dsVoucher = NULL;
lv_obj_t * ui_Container41 = NULL;
lv_obj_t * ui_dsInfoCaption5 = NULL;
lv_obj_t * ui_dsUnitPrice = NULL;
lv_obj_t * ui_Container42 = NULL;
lv_obj_t * ui_dsInfoCaption6 = NULL;
lv_obj_t * ui_dsUpdated = NULL;
// event funtions
void ui_event_dsInfoSCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_dsMainSCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_dsMainSCREEN_screen_init);
    }
}

// build funtions

void ui_dsInfoSCREEN_screen_init(void)
{
    ui_dsInfoSCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dsInfoSCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container35 = lv_obj_create(ui_dsInfoSCREEN);
    lv_obj_remove_style_all(ui_Container35);
    lv_obj_set_width(ui_Container35, lv_pct(100));
    lv_obj_set_height(ui_Container35, lv_pct(100));
    lv_obj_set_align(ui_Container35, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container35, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container35, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container35, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container35, &ui_img_934861631, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container40 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container40);
    lv_obj_set_width(ui_Container40, 309);
    lv_obj_set_height(ui_Container40, 18);
    lv_obj_set_x(ui_Container40, -100);
    lv_obj_set_y(ui_Container40, -217);
    lv_obj_set_align(ui_Container40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container40, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container36 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container36);
    lv_obj_set_width(ui_Container36, 340);
    lv_obj_set_height(ui_Container36, 30);
    lv_obj_set_x(ui_Container36, 11);
    lv_obj_set_y(ui_Container36, -105);
    lv_obj_set_align(ui_Container36, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container36, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container36, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container36, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsInfoCaption1 = lv_label_create(ui_Container36);
    lv_obj_set_width(ui_dsInfoCaption1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsInfoCaption1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsInfoCaption1, -82);
    lv_obj_set_y(ui_dsInfoCaption1, -146);
    lv_obj_set_align(ui_dsInfoCaption1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsInfoCaption1, "State:");
    lv_obj_set_style_text_color(ui_dsInfoCaption1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsInfoCaption1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsInfoCaption1, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsState = lv_label_create(ui_Container36);
    lv_obj_set_width(ui_dsState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsState, 38);
    lv_obj_set_y(ui_dsState, -149);
    lv_obj_set_align(ui_dsState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsState, "N/A");
    lv_obj_set_style_text_color(ui_dsState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsState, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container38 = lv_obj_create(ui_Container36);
    lv_obj_remove_style_all(ui_Container38);
    lv_obj_set_width(ui_Container38, 30);
    lv_obj_set_height(ui_Container38, 17);
    lv_obj_set_x(ui_Container38, -82);
    lv_obj_set_y(ui_Container38, -138);
    lv_obj_set_align(ui_Container38, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container38, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsInfoCaption2 = lv_label_create(ui_Container36);
    lv_obj_set_width(ui_dsInfoCaption2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsInfoCaption2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsInfoCaption2, -87);
    lv_obj_set_y(ui_dsInfoCaption2, -93);
    lv_obj_set_align(ui_dsInfoCaption2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsInfoCaption2, "Plan:");
    lv_obj_set_style_text_color(ui_dsInfoCaption2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsInfoCaption2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsInfoCaption2, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsPlan = lv_label_create(ui_Container36);
    lv_obj_set_width(ui_dsPlan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsPlan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsPlan, 27);
    lv_obj_set_y(ui_dsPlan, -94);
    lv_obj_set_align(ui_dsPlan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsPlan, "--");
    lv_obj_set_style_text_color(ui_dsPlan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsPlan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsPlan, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container37 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container37);
    lv_obj_set_width(ui_Container37, 340);
    lv_obj_set_height(ui_Container37, 30);
    lv_obj_set_x(ui_Container37, -75);
    lv_obj_set_y(ui_Container37, -112);
    lv_obj_set_align(ui_Container37, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container37, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container37, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container37, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsInfoCaption3 = lv_label_create(ui_Container37);
    lv_obj_set_width(ui_dsInfoCaption3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsInfoCaption3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsInfoCaption3, -76);
    lv_obj_set_y(ui_dsInfoCaption3, -109);
    lv_obj_set_align(ui_dsInfoCaption3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsInfoCaption3, "Cash:");
    lv_obj_set_style_text_color(ui_dsInfoCaption3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsInfoCaption3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsInfoCaption3, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsCash = lv_label_create(ui_Container37);
    lv_obj_set_width(ui_dsCash, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsCash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsCash, 26);
    lv_obj_set_y(ui_dsCash, -122);
    lv_obj_set_align(ui_dsCash, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsCash, "--");
    lv_obj_set_style_text_color(ui_dsCash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsCash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsCash, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container39 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container39);
    lv_obj_set_width(ui_Container39, 340);
    lv_obj_set_height(ui_Container39, 30);
    lv_obj_set_x(ui_Container39, -82);
    lv_obj_set_y(ui_Container39, -127);
    lv_obj_set_align(ui_Container39, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container39, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container39, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container39, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsInfoCaption4 = lv_label_create(ui_Container39);
    lv_obj_set_width(ui_dsInfoCaption4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsInfoCaption4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsInfoCaption4, -73);
    lv_obj_set_y(ui_dsInfoCaption4, -69);
    lv_obj_set_align(ui_dsInfoCaption4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsInfoCaption4, "Voucher:");
    lv_obj_set_style_text_color(ui_dsInfoCaption4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsInfoCaption4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsInfoCaption4, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsVoucher = lv_label_create(ui_Container39);
    lv_obj_set_width(ui_dsVoucher, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsVoucher, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsVoucher, 93);
    lv_obj_set_y(ui_dsVoucher, -78);
    lv_obj_set_align(ui_dsVoucher, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsVoucher, "--");
    lv_obj_set_style_text_color(ui_dsVoucher, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsVoucher, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsVoucher, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container41 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container41);
    lv_obj_set_width(ui_Container41, 340);
    lv_obj_set_height(ui_Container41, 30);
    lv_obj_set_x(ui_Container41, -113);
    lv_obj_set_y(ui_Container41, -67);
    lv_obj_set_align(ui_Container41, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container41, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container41, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container41, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsInfoCaption5 = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_dsInfoCaption5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsInfoCaption5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsInfoCaption5, -127);
    lv_obj_set_y(ui_dsInfoCaption5, -87);
    lv_obj_set_align(ui_dsInfoCaption5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsInfoCaption5, "Price:");
    lv_obj_set_style_text_color(ui_dsInfoCaption5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsInfoCaption5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsInfoCaption5, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsUnitPrice = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_dsUnitPrice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsUnitPrice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsUnitPrice, -38);
    lv_obj_set_y(ui_dsUnitPrice, -85);
    lv_obj_set_align(ui_dsUnitPrice, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsUnitPrice, "--");
    lv_obj_set_style_text_color(ui_dsUnitPrice, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsUnitPrice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsUnitPrice, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container42 = lv_obj_create(ui_Container41);
    lv_obj_remove_style_all(ui_Container42);
    lv_obj_set_width(ui_Container42, 18);
    lv_obj_set_height(ui_Container42, 9);
    lv_obj_set_x(ui_Container42, -50);
    lv_obj_set_y(ui_Container42, -101);
    lv_obj_set_align(ui_Container42, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container42, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dsInfoCaption6 = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_dsInfoCaption6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsInfoCaption6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsInfoCaption6, 77);
    lv_obj_set_y(ui_dsInfoCaption6, -85);
    lv_obj_set_align(ui_dsInfoCaption6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsInfoCaption6, "Updated:");
    lv_obj_set_style_text_color(ui_dsInfoCaption6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsInfoCaption6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsInfoCaption6, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dsUpdated = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_dsUpdated, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dsUpdated, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dsUpdated, 85);
    lv_obj_set_y(ui_dsUpdated, -93);
    lv_obj_set_align(ui_dsUpdated, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dsUpdated, "--");
    lv_obj_set_style_text_color(ui_dsUpdated, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dsUpdated, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dsUpdated, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_dsInfoSCREEN, ui_event_dsInfoSCREEN, LV_EVENT_ALL, NULL);

}

void ui_dsInfoSCREEN_screen_destroy(void)
{
    if(ui_dsInfoSCREEN) lv_obj_del(ui_dsInfoSCREEN);

    // NULL screen variables
    ui_dsInfoSCREEN = NULL;
    ui_Container35 = NULL;
    ui_Container40 = NULL;
    ui_Container36 = NULL;
    ui_dsInfoCaption1 = NULL;
    ui_dsState = NULL;
    ui_Container38 = NULL;
    ui_dsInfoCaption2 = NULL;
    ui_dsPlan = NULL;
    ui_Container37 = NULL;
    ui_dsInfoCaption3 = NULL;
    ui_dsCash = NULL;
    ui_Container39 = NULL;
    ui_dsInfoCaption4 = NULL;
    ui_dsVoucher = NULL;
    ui_Container41 = NULL;
    ui_dsInfoCaption5 = NULL;
    ui_dsUnitPrice = NULL;
    ui_Container42 = NULL;
    ui_dsInfoCaption6 = NULL;
    ui_dsUpdated = NULL;

}

void ui_dsInfoSCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
