// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DSINFOSCREEN_H
#define UI_DSINFOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dsInfoSCREEN
extern void ui_dsInfoSCREEN_screen_init(void);
extern void ui_dsInfoSCREEN_screen_destroy(void);
extern void ui_dsInfoSCREEN_screen_relocalize(void);
extern void ui_event_dsInfoSCREEN(lv_event_t * e);
extern lv_obj_t * ui_dsInfoSCREEN;
extern lv_obj_t * ui_Container35;
extern lv_obj_t * ui_Container40;
extern lv_obj_t * ui_Container36;
extern lv_obj_t * ui_dsInfoCaption1;
extern lv_obj_t * ui_dsState;
extern lv_obj_t * ui_Container38;
extern lv_obj_t * ui_dsInfoCaption2;
extern lv_obj_t * ui_dsPlan;
extern lv_obj_t * ui_Container37;
extern lv_obj_t * ui_dsInfoCaption3;
extern lv_obj_t * ui_dsCash;
extern lv_obj_t * ui_Container39;
extern lv_obj_t * ui_dsInfoCaption4;
extern lv_obj_t * ui_dsVoucher;
extern lv_obj_t * ui_Container41;
extern lv_obj_t * ui_dsInfoCaption5;
extern lv_obj_t * ui_dsUnitPrice;
extern lv_obj_t * ui_Container42;
extern lv_obj_t * ui_dsInfoCaption6;
extern lv_obj_t * ui_dsUpdated;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

