// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_KIMIINFOSCREEN_H
#define UI_KIMIINFOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_kimiInfoSCREEN
extern void ui_kimiInfoSCREEN_screen_init(void);
extern void ui_kimiInfoSCREEN_screen_destroy(void);
extern void ui_kimiInfoSCREEN_screen_relocalize(void);
extern void ui_event_kimiInfoSCREEN(lv_event_t * e);
extern lv_obj_t * ui_kimiInfoSCREEN;
extern lv_obj_t * ui_Container43;
extern lv_obj_t * ui_Container44;
extern lv_obj_t * ui_Container45;
extern lv_obj_t * ui_kimiInfoCaption1;
extern lv_obj_t * ui_kimiState;
extern lv_obj_t * ui_Container46;
extern lv_obj_t * ui_kimiInfoCaption2;
extern lv_obj_t * ui_kimiPlan;
extern lv_obj_t * ui_Container47;
extern lv_obj_t * ui_kimiInfoCaption3;
extern lv_obj_t * ui_kimiWeeklyRaw;
extern lv_obj_t * ui_Container48;
extern lv_obj_t * ui_kimiInfoCaption4;
extern lv_obj_t * ui_kimiWin5hRaw;
extern lv_obj_t * ui_Container49;
extern lv_obj_t * ui_kimiInfoCaption5;
extern lv_obj_t * ui_kimiWeeklyResetAt;
extern lv_obj_t * ui_Container50;
extern lv_obj_t * ui_kimiInfoCaption6;
extern lv_obj_t * ui_kimiUpdated;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

