// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_kimiInfoSCREEN = NULL;
lv_obj_t * ui_Container43 = NULL;
lv_obj_t * ui_Container44 = NULL;
lv_obj_t * ui_Container45 = NULL;
lv_obj_t * ui_kimiInfoCaption1 = NULL;
lv_obj_t * ui_kimiState = NULL;
lv_obj_t * ui_Container46 = NULL;
lv_obj_t * ui_kimiInfoCaption2 = NULL;
lv_obj_t * ui_kimiPlan = NULL;
lv_obj_t * ui_Container47 = NULL;
lv_obj_t * ui_kimiInfoCaption3 = NULL;
lv_obj_t * ui_kimiWeeklyRaw = NULL;
lv_obj_t * ui_Container48 = NULL;
lv_obj_t * ui_kimiInfoCaption4 = NULL;
lv_obj_t * ui_kimiWin5hRaw = NULL;
lv_obj_t * ui_Container49 = NULL;
lv_obj_t * ui_kimiInfoCaption5 = NULL;
lv_obj_t * ui_kimiWeeklyResetAt = NULL;
lv_obj_t * ui_Container50 = NULL;
lv_obj_t * ui_kimiInfoCaption6 = NULL;
lv_obj_t * ui_kimiUpdated = NULL;
// event funtions
void ui_event_kimiInfoSCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_kimiMainSCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_kimiMainSCREEN_screen_init);
    }
}

// build funtions

void ui_kimiInfoSCREEN_screen_init(void)
{
    ui_kimiInfoSCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_kimiInfoSCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container43 = lv_obj_create(ui_kimiInfoSCREEN);
    lv_obj_remove_style_all(ui_Container43);
    lv_obj_set_width(ui_Container43, lv_pct(100));
    lv_obj_set_height(ui_Container43, lv_pct(100));
    lv_obj_set_align(ui_Container43, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container43, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container43, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container43, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container43, &ui_img_934861631, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container44 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container44);
    lv_obj_set_width(ui_Container44, 309);
    lv_obj_set_height(ui_Container44, 18);
    lv_obj_set_x(ui_Container44, -100);
    lv_obj_set_y(ui_Container44, -217);
    lv_obj_set_align(ui_Container44, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container44, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container45 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container45);
    lv_obj_set_width(ui_Container45, 340);
    lv_obj_set_height(ui_Container45, 30);
    lv_obj_set_x(ui_Container45, 11);
    lv_obj_set_y(ui_Container45, -105);
    lv_obj_set_align(ui_Container45, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container45, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container45, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container45, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiInfoCaption1 = lv_label_create(ui_Container45);
    lv_obj_set_width(ui_kimiInfoCaption1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiInfoCaption1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiInfoCaption1, -82);
    lv_obj_set_y(ui_kimiInfoCaption1, -146);
    lv_obj_set_align(ui_kimiInfoCaption1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiInfoCaption1, "State:");
    lv_obj_set_style_text_color(ui_kimiInfoCaption1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiInfoCaption1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiInfoCaption1, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kimiState = lv_label_create(ui_Container45);
    lv_obj_set_width(ui_kimiState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiState, 38);
    lv_obj_set_y(ui_kimiState, -149);
    lv_obj_set_align(ui_kimiState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiState, "N/A");
    lv_obj_set_style_text_color(ui_kimiState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiState, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container46 = lv_obj_create(ui_Container45);
    lv_obj_remove_style_all(ui_Container46);
    lv_obj_set_width(ui_Container46, 30);
    lv_obj_set_height(ui_Container46, 17);
    lv_obj_set_x(ui_Container46, -82);
    lv_obj_set_y(ui_Container46, -138);
    lv_obj_set_align(ui_Container46, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container46, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiInfoCaption2 = lv_label_create(ui_Container45);
    lv_obj_set_width(ui_kimiInfoCaption2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiInfoCaption2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiInfoCaption2, -87);
    lv_obj_set_y(ui_kimiInfoCaption2, -93);
    lv_obj_set_align(ui_kimiInfoCaption2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiInfoCaption2, "Plan:");
    lv_obj_set_style_text_color(ui_kimiInfoCaption2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiInfoCaption2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiInfoCaption2, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kimiPlan = lv_label_create(ui_Container45);
    lv_obj_set_width(ui_kimiPlan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiPlan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiPlan, 27);
    lv_obj_set_y(ui_kimiPlan, -94);
    lv_obj_set_align(ui_kimiPlan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiPlan, "--");
    lv_obj_set_style_text_color(ui_kimiPlan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiPlan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiPlan, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container47 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container47);
    lv_obj_set_width(ui_Container47, 340);
    lv_obj_set_height(ui_Container47, 30);
    lv_obj_set_x(ui_Container47, -75);
    lv_obj_set_y(ui_Container47, -112);
    lv_obj_set_align(ui_Container47, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container47, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container47, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container47, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiInfoCaption3 = lv_label_create(ui_Container47);
    lv_obj_set_width(ui_kimiInfoCaption3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiInfoCaption3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiInfoCaption3, -76);
    lv_obj_set_y(ui_kimiInfoCaption3, -109);
    lv_obj_set_align(ui_kimiInfoCaption3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiInfoCaption3, "7d Used:");
    lv_obj_set_style_text_color(ui_kimiInfoCaption3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiInfoCaption3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiInfoCaption3, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kimiWeeklyRaw = lv_label_create(ui_Container47);
    lv_obj_set_width(ui_kimiWeeklyRaw, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiWeeklyRaw, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiWeeklyRaw, 26);
    lv_obj_set_y(ui_kimiWeeklyRaw, -122);
    lv_obj_set_align(ui_kimiWeeklyRaw, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiWeeklyRaw, "--");
    lv_obj_set_style_text_color(ui_kimiWeeklyRaw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiWeeklyRaw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiWeeklyRaw, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container48 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container48);
    lv_obj_set_width(ui_Container48, 340);
    lv_obj_set_height(ui_Container48, 30);
    lv_obj_set_x(ui_Container48, -82);
    lv_obj_set_y(ui_Container48, -127);
    lv_obj_set_align(ui_Container48, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container48, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container48, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container48, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiInfoCaption4 = lv_label_create(ui_Container48);
    lv_obj_set_width(ui_kimiInfoCaption4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiInfoCaption4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiInfoCaption4, -73);
    lv_obj_set_y(ui_kimiInfoCaption4, -69);
    lv_obj_set_align(ui_kimiInfoCaption4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiInfoCaption4, "5h Used:");
    lv_obj_set_style_text_color(ui_kimiInfoCaption4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiInfoCaption4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiInfoCaption4, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kimiWin5hRaw = lv_label_create(ui_Container48);
    lv_obj_set_width(ui_kimiWin5hRaw, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiWin5hRaw, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiWin5hRaw, 93);
    lv_obj_set_y(ui_kimiWin5hRaw, -78);
    lv_obj_set_align(ui_kimiWin5hRaw, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiWin5hRaw, "--");
    lv_obj_set_style_text_color(ui_kimiWin5hRaw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiWin5hRaw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiWin5hRaw, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container49 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container49);
    lv_obj_set_width(ui_Container49, 340);
    lv_obj_set_height(ui_Container49, 30);
    lv_obj_set_x(ui_Container49, -113);
    lv_obj_set_y(ui_Container49, -67);
    lv_obj_set_align(ui_Container49, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container49, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container49, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container49, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiInfoCaption5 = lv_label_create(ui_Container49);
    lv_obj_set_width(ui_kimiInfoCaption5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiInfoCaption5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiInfoCaption5, -127);
    lv_obj_set_y(ui_kimiInfoCaption5, -87);
    lv_obj_set_align(ui_kimiInfoCaption5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiInfoCaption5, "7d ResetAt:");
    lv_obj_set_style_text_color(ui_kimiInfoCaption5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiInfoCaption5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiInfoCaption5, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kimiWeeklyResetAt = lv_label_create(ui_Container49);
    lv_obj_set_width(ui_kimiWeeklyResetAt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiWeeklyResetAt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiWeeklyResetAt, -38);
    lv_obj_set_y(ui_kimiWeeklyResetAt, -85);
    lv_obj_set_align(ui_kimiWeeklyResetAt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiWeeklyResetAt, "--");
    lv_obj_set_style_text_color(ui_kimiWeeklyResetAt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiWeeklyResetAt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiWeeklyResetAt, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container50 = lv_obj_create(ui_Container49);
    lv_obj_remove_style_all(ui_Container50);
    lv_obj_set_width(ui_Container50, 18);
    lv_obj_set_height(ui_Container50, 9);
    lv_obj_set_x(ui_Container50, -50);
    lv_obj_set_y(ui_Container50, -101);
    lv_obj_set_align(ui_Container50, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container50, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiInfoCaption6 = lv_label_create(ui_Container49);
    lv_obj_set_width(ui_kimiInfoCaption6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiInfoCaption6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiInfoCaption6, 77);
    lv_obj_set_y(ui_kimiInfoCaption6, -85);
    lv_obj_set_align(ui_kimiInfoCaption6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiInfoCaption6, "Updated:");
    lv_obj_set_style_text_color(ui_kimiInfoCaption6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiInfoCaption6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiInfoCaption6, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kimiUpdated = lv_label_create(ui_Container49);
    lv_obj_set_width(ui_kimiUpdated, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiUpdated, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiUpdated, 85);
    lv_obj_set_y(ui_kimiUpdated, -93);
    lv_obj_set_align(ui_kimiUpdated, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiUpdated, "--");
    lv_obj_set_style_text_color(ui_kimiUpdated, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiUpdated, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiUpdated, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_kimiInfoSCREEN, ui_event_kimiInfoSCREEN, LV_EVENT_ALL, NULL);

}

void ui_kimiInfoSCREEN_screen_destroy(void)
{
    if(ui_kimiInfoSCREEN) lv_obj_del(ui_kimiInfoSCREEN);

    // NULL screen variables
    ui_kimiInfoSCREEN = NULL;
    ui_Container43 = NULL;
    ui_Container44 = NULL;
    ui_Container45 = NULL;
    ui_kimiInfoCaption1 = NULL;
    ui_kimiState = NULL;
    ui_Container46 = NULL;
    ui_kimiInfoCaption2 = NULL;
    ui_kimiPlan = NULL;
    ui_Container47 = NULL;
    ui_kimiInfoCaption3 = NULL;
    ui_kimiWeeklyRaw = NULL;
    ui_Container48 = NULL;
    ui_kimiInfoCaption4 = NULL;
    ui_kimiWin5hRaw = NULL;
    ui_Container49 = NULL;
    ui_kimiInfoCaption5 = NULL;
    ui_kimiWeeklyResetAt = NULL;
    ui_Container50 = NULL;
    ui_kimiInfoCaption6 = NULL;
    ui_kimiUpdated = NULL;

}

void ui_kimiInfoSCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
