// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_kimiMainSCREEN = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Container18 = NULL;
lv_obj_t * ui_kimiWeeklyValue = NULL;
lv_obj_t * ui_Container19 = NULL;
lv_obj_t * ui_Container20 = NULL;
lv_obj_t * ui_kimiCaption1 = NULL;
lv_obj_t * ui_kimiWin5h = NULL;
lv_obj_t * ui_Container21 = NULL;
lv_obj_t * ui_kimiCaption2 = NULL;
lv_obj_t * ui_kimiWeeklyReset = NULL;
lv_obj_t * ui_Container22 = NULL;
lv_obj_t * ui_kimiCaption3 = NULL;
lv_obj_t * ui_kimiWin5hReset = NULL;
// event funtions
void ui_event_kimiMainSCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_standbySCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_standbySCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_dsMainSCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dsMainSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_kimiInfoSCREEN, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_kimiInfoSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_overviewSCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_overviewSCREEN_screen_init);
    }
}

// build funtions

void ui_kimiMainSCREEN_screen_init(void)
{
    ui_kimiMainSCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_kimiMainSCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container17 = lv_obj_create(ui_kimiMainSCREEN);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, lv_pct(100));
    lv_obj_set_height(ui_Container17, lv_pct(100));
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container17, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container17, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container17, &ui_img_919862230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 246);
    lv_obj_set_height(ui_Container18, 22);
    lv_obj_set_x(ui_Container18, -30);
    lv_obj_set_y(ui_Container18, -174);
    lv_obj_set_align(ui_Container18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiWeeklyValue = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_kimiWeeklyValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiWeeklyValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiWeeklyValue, -5);
    lv_obj_set_y(ui_kimiWeeklyValue, -193);
    lv_obj_set_align(ui_kimiWeeklyValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiWeeklyValue, "--");
    lv_obj_set_style_text_color(ui_kimiWeeklyValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiWeeklyValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiWeeklyValue, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 246);
    lv_obj_set_height(ui_Container19, 15);
    lv_obj_set_x(ui_Container19, -30);
    lv_obj_set_y(ui_Container19, -174);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container20 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 260);
    lv_obj_set_height(ui_Container20, 45);
    lv_obj_set_x(ui_Container20, -152);
    lv_obj_set_y(ui_Container20, -127);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container20, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container20, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiCaption1 = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_kimiCaption1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiCaption1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiCaption1, -86);
    lv_obj_set_y(ui_kimiCaption1, -125);
    lv_obj_set_align(ui_kimiCaption1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiCaption1, "5h Quota:");
    lv_obj_set_style_text_color(ui_kimiCaption1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiCaption1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiCaption1, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kimiWin5h = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_kimiWin5h, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiWin5h, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiWin5h, 33);
    lv_obj_set_y(ui_kimiWin5h, -126);
    lv_obj_set_align(ui_kimiWin5h, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiWin5h, "--");
    lv_obj_set_style_text_color(ui_kimiWin5h, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiWin5h, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiWin5h, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container21 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 260);
    lv_obj_set_height(ui_Container21, 45);
    lv_obj_set_x(ui_Container21, -100);
    lv_obj_set_y(ui_Container21, -131);
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container21, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container21, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiCaption2 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_kimiCaption2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiCaption2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiCaption2, -88);
    lv_obj_set_y(ui_kimiCaption2, -68);
    lv_obj_set_align(ui_kimiCaption2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiCaption2, "7d Reset:");
    lv_obj_set_style_text_color(ui_kimiCaption2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiCaption2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiCaption2, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kimiWeeklyReset = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_kimiWeeklyReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiWeeklyReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiWeeklyReset, 26);
    lv_obj_set_y(ui_kimiWeeklyReset, -71);
    lv_obj_set_align(ui_kimiWeeklyReset, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_kimiWeeklyReset, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_kimiWeeklyReset, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_kimiWeeklyReset, "--");
    lv_obj_set_style_text_color(ui_kimiWeeklyReset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiWeeklyReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiWeeklyReset, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container22 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 260);
    lv_obj_set_height(ui_Container22, 45);
    lv_obj_set_x(ui_Container22, -116);
    lv_obj_set_y(ui_Container22, -170);
    lv_obj_set_align(ui_Container22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container22, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container22, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kimiCaption3 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_kimiCaption3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiCaption3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiCaption3, -91);
    lv_obj_set_y(ui_kimiCaption3, -21);
    lv_obj_set_align(ui_kimiCaption3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiCaption3, "5h Reset:");
    lv_obj_set_style_text_color(ui_kimiCaption3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiCaption3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiCaption3, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kimiWin5hReset = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_kimiWin5hReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kimiWin5hReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kimiWin5hReset, 41);
    lv_obj_set_y(ui_kimiWin5hReset, -17);
    lv_obj_set_align(ui_kimiWin5hReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kimiWin5hReset, "--");
    lv_obj_set_style_text_color(ui_kimiWin5hReset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kimiWin5hReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kimiWin5hReset, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_kimiMainSCREEN, ui_event_kimiMainSCREEN, LV_EVENT_ALL, NULL);

}

void ui_kimiMainSCREEN_screen_destroy(void)
{
    if(ui_kimiMainSCREEN) lv_obj_del(ui_kimiMainSCREEN);

    // NULL screen variables
    ui_kimiMainSCREEN = NULL;
    ui_Container17 = NULL;
    ui_Container18 = NULL;
    ui_kimiWeeklyValue = NULL;
    ui_Container19 = NULL;
    ui_Container20 = NULL;
    ui_kimiCaption1 = NULL;
    ui_kimiWin5h = NULL;
    ui_Container21 = NULL;
    ui_kimiCaption2 = NULL;
    ui_kimiWeeklyReset = NULL;
    ui_Container22 = NULL;
    ui_kimiCaption3 = NULL;
    ui_kimiWin5hReset = NULL;

}

void ui_kimiMainSCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
