// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_KIMIMAINSCREEN_H
#define UI_KIMIMAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_kimiMainSCREEN
extern void ui_kimiMainSCREEN_screen_init(void);
extern void ui_kimiMainSCREEN_screen_destroy(void);
extern void ui_kimiMainSCREEN_screen_relocalize(void);
extern void ui_event_kimiMainSCREEN(lv_event_t * e);
extern lv_obj_t * ui_kimiMainSCREEN;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_kimiWeeklyValue;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_kimiCaption1;
extern lv_obj_t * ui_kimiWin5h;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_kimiCaption2;
extern lv_obj_t * ui_kimiWeeklyReset;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_kimiCaption3;
extern lv_obj_t * ui_kimiWin5hReset;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

