// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_OVERVIEWSCREEN_H
#define UI_OVERVIEWSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_overviewSCREEN
extern void ui_overviewSCREEN_screen_init(void);
extern void ui_overviewSCREEN_screen_destroy(void);
extern void ui_overviewSCREEN_screen_relocalize(void);
extern void ui_event_overviewSCREEN(lv_event_t * e);
extern lv_obj_t * ui_overviewSCREEN;
extern lv_obj_t * ui_overviewwallpaper;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_totalcostlabel;
extern lv_obj_t * ui_overviewContainer1;
extern void ui_event_slot1btn(lv_event_t * e);
extern lv_obj_t * ui_slot1btn;
extern lv_obj_t * ui_slot1title;
extern lv_obj_t * ui_slot1value;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_slot1bar;
extern void ui_event_slot2btn(lv_event_t * e);
extern lv_obj_t * ui_slot2btn;
extern lv_obj_t * ui_slot2title;
extern lv_obj_t * ui_slot2value;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_slot2bar;
extern lv_obj_t * ui_overviewContainer2;
extern void ui_event_slot3btn(lv_event_t * e);
extern lv_obj_t * ui_slot3btn;
extern lv_obj_t * ui_slot3title;
extern lv_obj_t * ui_slot3value;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_slot3bar;
extern void ui_event_slot4btn(lv_event_t * e);
extern lv_obj_t * ui_slot4btn;
extern lv_obj_t * ui_slot4title;
extern lv_obj_t * ui_slot4value;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_slot4bar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

