// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_overviewSCREEN = NULL;
lv_obj_t * ui_overviewwallpaper = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_totalcostlabel = NULL;
lv_obj_t * ui_overviewContainer1 = NULL;
lv_obj_t * ui_slot1btn = NULL;
lv_obj_t * ui_slot1title = NULL;
lv_obj_t * ui_slot1value = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_slot1bar = NULL;
lv_obj_t * ui_slot2btn = NULL;
lv_obj_t * ui_slot2title = NULL;
lv_obj_t * ui_slot2value = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_slot2bar = NULL;
lv_obj_t * ui_overviewContainer2 = NULL;
lv_obj_t * ui_slot3btn = NULL;
lv_obj_t * ui_slot3title = NULL;
lv_obj_t * ui_slot3value = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_slot3bar = NULL;
lv_obj_t * ui_slot4btn = NULL;
lv_obj_t * ui_slot4title = NULL;
lv_obj_t * ui_slot4value = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_slot4bar = NULL;
// event funtions
void ui_event_overviewSCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_standbySCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_standbySCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_dsMainSCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_dsMainSCREEN_screen_init);
    }
}

void ui_event_slot1btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dsMainSCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_dsMainSCREEN_screen_init);
    }
}

void ui_event_slot2btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dsMainSCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_dsMainSCREEN_screen_init);
    }
}

void ui_event_slot3btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_kimiMainSCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_kimiMainSCREEN_screen_init);
    }
}

void ui_event_slot4btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_kimiMainSCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_kimiMainSCREEN_screen_init);
    }
}

// build funtions

void ui_overviewSCREEN_screen_init(void)
{
    ui_overviewSCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_overviewSCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_overviewwallpaper = lv_obj_create(ui_overviewSCREEN);
    lv_obj_remove_style_all(ui_overviewwallpaper);
    lv_obj_set_width(ui_overviewwallpaper, lv_pct(100));
    lv_obj_set_height(ui_overviewwallpaper, lv_pct(100));
    lv_obj_set_align(ui_overviewwallpaper, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_overviewwallpaper, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_overviewwallpaper, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_overviewwallpaper, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_overviewwallpaper, &ui_img_411710101, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_overviewwallpaper);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 219);
    lv_obj_set_height(ui_Container10, 19);
    lv_obj_set_x(ui_Container10, -100);
    lv_obj_set_y(ui_Container10, -163);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_totalcostlabel = lv_label_create(ui_overviewwallpaper);
    lv_obj_set_width(ui_totalcostlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalcostlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalcostlabel, 9);
    lv_obj_set_y(ui_totalcostlabel, -161);
    lv_obj_set_align(ui_totalcostlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalcostlabel, "--");
    lv_obj_set_style_text_color(ui_totalcostlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_totalcostlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_totalcostlabel, &ui_font_DaoLiti72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overviewContainer1 = lv_obj_create(ui_overviewwallpaper);
    lv_obj_remove_style_all(ui_overviewContainer1);
    lv_obj_set_width(ui_overviewContainer1, 368);
    lv_obj_set_height(ui_overviewContainer1, 73);
    lv_obj_set_x(ui_overviewContainer1, 56);
    lv_obj_set_y(ui_overviewContainer1, -67);
    lv_obj_set_align(ui_overviewContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_overviewContainer1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_overviewContainer1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_overviewContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slot1btn = lv_btn_create(ui_overviewContainer1);
    lv_obj_set_width(ui_slot1btn, 180);
    lv_obj_set_height(ui_slot1btn, 50);
    lv_obj_set_x(ui_slot1btn, -95);
    lv_obj_set_y(ui_slot1btn, -94);
    lv_obj_set_align(ui_slot1btn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_slot1btn, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_slot1btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_slot1btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_slot1btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slot1btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot1btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot1title = lv_label_create(ui_slot1btn);
    lv_obj_set_width(ui_slot1title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slot1title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slot1title, -157);
    lv_obj_set_y(ui_slot1title, -109);
    lv_obj_set_align(ui_slot1title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slot1title, "DS Bal: ");
    lv_obj_set_style_text_color(ui_slot1title, lv_color_hex(0x0F5D08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot1title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot1title, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot1value = lv_label_create(ui_slot1btn);
    lv_obj_set_width(ui_slot1value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slot1value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slot1value, -97);
    lv_obj_set_y(ui_slot1value, -76);
    lv_obj_set_align(ui_slot1value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slot1value, "--");
    lv_obj_set_style_text_color(ui_slot1value, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot1value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot1value, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_slot1btn);
    lv_img_set_src(ui_Image12, &ui_img_334752297);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image12, 89);
    lv_obj_set_y(ui_Image12, 39);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slot1bar = lv_bar_create(ui_Image12);
    lv_bar_set_value(ui_slot1bar, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_slot1bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slot1bar, 117);
    lv_obj_set_height(ui_slot1bar, 17);
    lv_obj_set_x(ui_slot1bar, -1);
    lv_obj_set_y(ui_slot1bar, 0);
    lv_obj_set_align(ui_slot1bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_slot1bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot1bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_slot1bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slot1bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot1bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slot1bar, &ui_img_888914300, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_slot1bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_slot1bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_slot2btn = lv_btn_create(ui_overviewContainer1);
    lv_obj_set_width(ui_slot2btn, 180);
    lv_obj_set_height(ui_slot2btn, 50);
    lv_obj_set_x(ui_slot2btn, 88);
    lv_obj_set_y(ui_slot2btn, -95);
    lv_obj_set_align(ui_slot2btn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_slot2btn, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_slot2btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_slot2btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_slot2btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slot2btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot2btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot2title = lv_label_create(ui_slot2btn);
    lv_obj_set_width(ui_slot2title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slot2title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slot2title, -157);
    lv_obj_set_y(ui_slot2title, -109);
    lv_obj_set_align(ui_slot2title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slot2title, "DS Cost: ");
    lv_obj_set_style_text_color(ui_slot2title, lv_color_hex(0x0F5D08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot2title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot2title, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot2value = lv_label_create(ui_slot2btn);
    lv_obj_set_width(ui_slot2value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slot2value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slot2value, 108);
    lv_obj_set_y(ui_slot2value, -73);
    lv_obj_set_align(ui_slot2value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slot2value, "--");
    lv_obj_set_style_text_color(ui_slot2value, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot2value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot2value, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_slot2btn);
    lv_img_set_src(ui_Image13, &ui_img_334752297);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image13, 89);
    lv_obj_set_y(ui_Image13, 39);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slot2bar = lv_bar_create(ui_Image13);
    lv_bar_set_value(ui_slot2bar, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_slot2bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slot2bar, 117);
    lv_obj_set_height(ui_slot2bar, 17);
    lv_obj_set_x(ui_slot2bar, -1);
    lv_obj_set_y(ui_slot2bar, 0);
    lv_obj_set_align(ui_slot2bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_slot2bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot2bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_slot2bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slot2bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot2bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slot2bar, &ui_img_888914300, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_slot2bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_slot2bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_overviewContainer2 = lv_obj_create(ui_overviewwallpaper);
    lv_obj_remove_style_all(ui_overviewContainer2);
    lv_obj_set_width(ui_overviewContainer2, 368);
    lv_obj_set_height(ui_overviewContainer2, 73);
    lv_obj_set_x(ui_overviewContainer2, -49);
    lv_obj_set_y(ui_overviewContainer2, -68);
    lv_obj_set_align(ui_overviewContainer2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_overviewContainer2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_overviewContainer2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_overviewContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slot3btn = lv_btn_create(ui_overviewContainer2);
    lv_obj_set_width(ui_slot3btn, 180);
    lv_obj_set_height(ui_slot3btn, 50);
    lv_obj_set_x(ui_slot3btn, -91);
    lv_obj_set_y(ui_slot3btn, -26);
    lv_obj_set_align(ui_slot3btn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_slot3btn, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_slot3btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_slot3btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_slot3btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slot3btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot3btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot3title = lv_label_create(ui_slot3btn);
    lv_obj_set_width(ui_slot3title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slot3title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slot3title, -157);
    lv_obj_set_y(ui_slot3title, -109);
    lv_obj_set_align(ui_slot3title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slot3title, "Kimi 5h: ");
    lv_obj_set_style_text_color(ui_slot3title, lv_color_hex(0x0F5D08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot3title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot3title, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot3value = lv_label_create(ui_slot3btn);
    lv_obj_set_width(ui_slot3value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slot3value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slot3value, -99);
    lv_obj_set_y(ui_slot3value, 3);
    lv_obj_set_align(ui_slot3value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slot3value, "--");
    lv_obj_set_style_text_color(ui_slot3value, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot3value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot3value, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_slot3btn);
    lv_img_set_src(ui_Image11, &ui_img_334752297);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image11, 89);
    lv_obj_set_y(ui_Image11, 39);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slot3bar = lv_bar_create(ui_Image11);
    lv_bar_set_value(ui_slot3bar, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_slot3bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slot3bar, 117);
    lv_obj_set_height(ui_slot3bar, 17);
    lv_obj_set_x(ui_slot3bar, -1);
    lv_obj_set_y(ui_slot3bar, 0);
    lv_obj_set_align(ui_slot3bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_slot3bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot3bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_slot3bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slot3bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot3bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slot3bar, &ui_img_888914300, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_slot3bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_slot3bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_slot4btn = lv_btn_create(ui_overviewContainer2);
    lv_obj_set_width(ui_slot4btn, 180);
    lv_obj_set_height(ui_slot4btn, 50);
    lv_obj_set_x(ui_slot4btn, 89);
    lv_obj_set_y(ui_slot4btn, -26);
    lv_obj_set_align(ui_slot4btn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_slot4btn, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_slot4btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_slot4btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_slot4btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slot4btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot4btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot4title = lv_label_create(ui_slot4btn);
    lv_obj_set_width(ui_slot4title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slot4title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slot4title, -157);
    lv_obj_set_y(ui_slot4title, -109);
    lv_obj_set_align(ui_slot4title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slot4title, "Kimi 7d: ");
    lv_obj_set_style_text_color(ui_slot4title, lv_color_hex(0x0F5D08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot4title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot4title, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot4value = lv_label_create(ui_slot4btn);
    lv_obj_set_width(ui_slot4value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slot4value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slot4value, 103);
    lv_obj_set_y(ui_slot4value, 1);
    lv_obj_set_align(ui_slot4value, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_slot4value, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_slot4value, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_slot4value, "--");
    lv_obj_set_style_text_color(ui_slot4value, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot4value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot4value, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_slot4btn);
    lv_img_set_src(ui_Image10, &ui_img_334752297);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image10, 89);
    lv_obj_set_y(ui_Image10, 39);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slot4bar = lv_bar_create(ui_Image10);
    lv_bar_set_value(ui_slot4bar, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_slot4bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slot4bar, 117);
    lv_obj_set_height(ui_slot4bar, 17);
    lv_obj_set_x(ui_slot4bar, -1);
    lv_obj_set_y(ui_slot4bar, 0);
    lv_obj_set_align(ui_slot4bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_slot4bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot4bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_slot4bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slot4bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot4bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slot4bar, &ui_img_888914300, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_slot4bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_slot4bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_slot1btn, ui_event_slot1btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_slot2btn, ui_event_slot2btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_slot3btn, ui_event_slot3btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_slot4btn, ui_event_slot4btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_overviewSCREEN, ui_event_overviewSCREEN, LV_EVENT_ALL, NULL);

}

void ui_overviewSCREEN_screen_destroy(void)
{
    if(ui_overviewSCREEN) lv_obj_del(ui_overviewSCREEN);

    // NULL screen variables
    ui_overviewSCREEN = NULL;
    ui_overviewwallpaper = NULL;
    ui_Container10 = NULL;
    ui_totalcostlabel = NULL;
    ui_overviewContainer1 = NULL;
    ui_slot1btn = NULL;
    ui_slot1title = NULL;
    ui_slot1value = NULL;
    ui_Image12 = NULL;
    ui_slot1bar = NULL;
    ui_slot2btn = NULL;
    ui_slot2title = NULL;
    ui_slot2value = NULL;
    ui_Image13 = NULL;
    ui_slot2bar = NULL;
    ui_overviewContainer2 = NULL;
    ui_slot3btn = NULL;
    ui_slot3title = NULL;
    ui_slot3value = NULL;
    ui_Image11 = NULL;
    ui_slot3bar = NULL;
    ui_slot4btn = NULL;
    ui_slot4title = NULL;
    ui_slot4value = NULL;
    ui_Image10 = NULL;
    ui_slot4bar = NULL;

}

void ui_overviewSCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
